name: Managed Connector CI

on:
  push:
    branches: [ cloud-rh-com ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Retrieve Project Metadata
        uses: radcortez/project-metadata-action@243817f1e0f2b4df4e012fc17efc45cff166425d
        id: metadata
        with:
          metadata-file-path: '.github/project.yaml'
          local-file: true

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Build docker image and push it
        run: |
          ADDITIONAL_TAGS="$(git log --pretty=format:'%h' -n 1)"
          docker login -u="${{secrets.IMAGE_REPO_USERNAME}}" -p="${{secrets.IMAGE_REPO_PASSWORD}}" ${{secrets.IMAGE_REPO_HOSTNAME}}
          docker build -t "${{secrets.IMAGE_REPO_HOSTNAME}}/${{secrets.IMAGE_REPO_NAMESPACE}}/cos-ui:latest" \
            -t "${{secrets.IMAGE_REPO_HOSTNAME}}/${{secrets.IMAGE_REPO_NAMESPACE}}/cos-ui:${{steps.metadata.outputs.current-version}}" \
            -t "${{secrets.IMAGE_REPO_HOSTNAME}}/${{secrets.IMAGE_REPO_NAMESPACE}}/cos-ui:${ADDITIONAL_TAGS}" .
          docker image push --all-tags "${{secrets.IMAGE_REPO_HOSTNAME}}/${{secrets.IMAGE_REPO_NAMESPACE}}/cos-ui"