name: Build and test
on: [push]
jobs:
  test:
    name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node modules
        id: yarn-cache
        uses: actions/cache@v2
        env:
            cache-name: cache-node-modules-v2
        with:
            path: |
                $(yarn cache dir)
                ~/.cache/Cypress
                node_modules
                */*/node_modules
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}-
                ${{ runner.os }}-build-
                ${{ runner.os }}-
      - name: Install dependencies if needed.
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --ignore-platform --frozen-lockfile

      - name: Build if cache has been restored.
        if: steps.yarn-cache.outputs.cache-hit == 'true'
        run: yarn build

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format